[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

# Test settings
[fuzz]
runs = 256

# RPC endpoints (for local development)
[rpc_endpoints]
local = "http://127.0.0.1:8545"
