name: Contracts CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'contracts/**', '.github/workflows/contracts-ci.yml' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'contracts/**', '.github/workflows/contracts-ci.yml' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Run tests
      run: |
        cd contracts
        forge build
        forge test

    - name: Run lints
      run: |
        cd contracts
        forge fmt --check
        forge build --sizes
