name: Rust CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'gateway/**', 'oracle/**', '.github/workflows/rust-ci.yml' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'gateway/**', 'oracle/**', '.github/workflows/rust-ci.yml' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --workspace
